name: "Composite Action"
description: "[Test] Composite Action"

inputs:
  tf_version:
    description: "test"
    required: true

runs:
  using: "composite"
  steps:
    - name: step1
      shell: bash
      run: echo 'Hello World'

    - name: step2
      shell: bash
      run: echo ${{ inputs.tf_version }}
