name: "tfcmt"
description: "tfcmt for pull_request"
inputs:
  cwd:
    description: "terraform plan するディレクトリ"
    required: true
  pr_number:
    description: "コメントするPR number"
    required: true

runs:
  using: "composite"
  steps:
    - name: "tfcmt"
      shell: bash
      run: |
        curl -s https://opendata-tools.s3.ap-northeast-1.amazonaws.com/tfcmt_linux_amd64.tar.gz | tar zxf - -C /usr/local/bin/ tfcmt
        tfcmt --var target:${{ inputs.cwd }} --owner stockmarkteam --repo inter --pr ${{ inputs.pr_number }} plan -patch -skip-no-changes -- terraform plan -no-color
