name: "AWS Assume Role Action"
description: "AssumeRole を実行して認証情報を得る"
inputs:
  aws_account_id:
    description: "assume-role 対象の aws account_id"
    required: true

runs:
  using: "composite"
  steps:
    - name: "AssumeRole"
      shell: bash
      run: |
        # echo '{"Credentials":{"AccessKeyId":"AAA","SecretAccessKey":"BBB","SessionToken":"CCC","Expiration":"2023-07-10T02:56:21+00:00"},"AssumedRoleUser":{"AssumedRoleId":"DDD","Arn":"EEE"}}' >/tmp/cred.json
        aws sts assume-role --role-arn arn:aws:iam::${{ inputs.aws_account_id }}:role/opendata-terraform-execution --role-session-name inter-gh-actions >/tmp/cred.json
        jq -r '"AWS_ACCESS_KEY_ID=\(.Credentials.AccessKeyId)"' /tmp/cred.json >> ${GITHUB_ENV}
        jq -r '"AWS_SECRET_ACCESS_KEY=\(.Credentials.SecretAccessKey)"' /tmp/cred.json >> ${GITHUB_ENV}
        jq -r '"AWS_SESSION_TOKEN=\(.Credentials.SessionToken)"' /tmp/cred.json >> ${GITHUB_ENV}

# 公式の action を使うやり方
# steps:
#   - name: Configure AWS credentials
#     uses: aws-actions/configure-aws-credentials@v2
#     with:
#       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       role-to-assume: arn:aws:iam::590706584222:role/opendata-terraform-execution
#       role-session-name: github-actions-session
#       aws-region: ${{ env.AWS_DEFAULT_REGION }}
#       role-skip-session-tagging: true
#       role-duration-seconds: 1200
