name: "reuse"

on:
  workflow_call:
    inputs:
      chdir:
        required: true
        type: string
      tf_version_file:
        required: true
        type: string

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: show env
        run: env | sort

      - name: get version
        run: echo TF_VERSION_FROM_FILE=$(cat ${{ inputs.tf_version_file }}) >> ${GITHUB_ENV}

      - name: check version
        run: echo "VERSION from file is ${{ env.TF_VERSION_FROM_FILE }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION_FROM_FILE }}

      - name: terraform version
        shell: bash
        working-directory: ${{ inputs.chdir }}
        run: terraform version
