name: "reuse"

on:
  workflow_call:
    inputs:
      cwd:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get-version
        run: echo TF_VERSION_FROM_FILE=$(cat infra/.terraform-version) >> ${GITHUB_ENV}

      - name: check version
        run: echo "VERSION from file is ${{ env.TF_VERSION_FROM_FILE }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: ${{ inputs.TF_VERSION }}
          terraform_version: ${{ env.TF_VERSION_FROM_FILE }}

      - name: terraform version
        shell: bash
        working-directory: ${{ inputs.cwd }}
        run: terraform version
