name: "_ terraform apply までの一連のフロー"

on:
  workflow_call:
    inputs:
      cwd:
        required: true
        type: string
        description: "terraform plan するディレクトリ"
      apply:
        required: false
        type: boolean
        description: "terraform apply まで実行するか？"
      TF_VERSION:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.TF_VERSION }}

      - name: terraform fmt
        working-directory: ${{ inputs.cwd }}
        run: terraform fmt -check -recursive

      - name: terraform init
        working-directory: ${{ inputs.cwd }}
        run: terraform init

      - name: terraform validate
        working-directory: ${{ inputs.cwd }}
        run: terraform validate

      - name: terraform plan
        working-directory: ${{ inputs.cwd }}
        run: terraform plan -no-color

      - name: terraform apply
        working-directory: ${{ inputs.cwd }}
        if: inputs.apply == true
        run: terraform apply -no-color -auto-approve
