name: "infra: PRマージ時の terraform apply"

on:
  push:
    paths:
      - infra/**
    branches:
      - main
      - release/**
      - develop
  workflow_dispatch:

env:
  TF_VERSION: 1.5.0
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  develop:
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/develop
      apply: true
      TF_VERSION: ${{ env.TF_VERSION }}

  staging:
    if: startsWith(github.ref_name, 'release/')
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/staging
      apply: true
      TF_VERSION: ${{ env.TF_VERSION }}

  production:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/production
      apply: true
      TF_VERSION: ${{ env.TF_VERSION }}
