name: "infra: トピックブランチ push 時の terraform plan"

on:
  push:
    paths:
      - infra/**
    branches-ignore:
      - main
      - release/**
      - develop
  workflow_dispatch:

env:
  TF_VERSION: 1.5.0
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  develop:
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/develop
      TF_VERSION: ${{ env.TF_VERSION }}

  staging:
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/staging
      TF_VERSION: ${{ env.TF_VERSION }}

  production:
    uses: ./.github/workflows/_terraform.yml
    with:
      cwd: ./infra/env/production
      TF_VERSION: ${{ env.TF_VERSION }}
