name: "matrix"

on:
  push:
  workflow_dispatch:

jobs:
  test-job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - development
          - staging
          - production

    env:
      ENV: ${{ matrix.env }}

    steps:
      - name: step1
        if: matrix.env == github.ref_name
        run: |
          echo '1' ${{ matrix.env }}
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

      - name: step2
        if: matrix.env == github.ref_name
        run: |
          env | sort
          echo $ENV
