on:
  workflow_call:
    inputs:
      TF_VERSION:
        required: true
        type: string
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string

env:
  TF_VERSION2: ${{ inputs.TF_VERSION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  reuse-test:
    runs-on: ubuntu-latest

    steps:
      - name: called
        run: |
          echo "called"
          pwd
          ls -la
          env | sort
          echo ${{ inputs.TF_VERSION }}
