on:
  workflow_call:
    inputs:
      TF_VERSION:
        required: true
        type: string

jobs:
  update-infra:
    runs-on: ubuntu-latest

    steps:
      - name: called
        run: |
          echo "called"
          pwd
          ls -la
          env | sort
          echo ${{ inputs.TF_VERSION }}
